### ISSUE TITLE
Problems with Spatie's permission.

### ISSUE THREAD

**Issue by anhtuanst1** [anhtuanst1/demo-tenancy#3]
Below are the scenario:
I have:

- Root site and Tenant site have separate databases.
- Root: has "super admin" role with full permissions.
- Tenant: has "system admin" role with full permisisons in tenant.

I do:

- As super admin, I change permission (e.g: uncheck permission Add User).

Expect:

- No affect to permission of system admin in tenant.

Actual:

- Permission of system admin in tenant get changes and vice versus. Although tenant's database no change ("Add User" permisison still checked in tenant's database).

I use @can to check permission in file resources/views/home.blade.php
I think I missed something in configuration in tenant.

**Comment by coding-sunshine** [comment]
@anhtuanst1 any luck with above?

**Comment by anhtuanst1** [comment]
> @anhtuanst1 any luck with above?

No, this issue has not been resolved.

**Comment by anhtuanst1** [comment]
Resolved by [stancl](https://github.com/stancl/tenancy/issues/230#issuecomment-574738529)
